# Generated by Django 4.2.30 on 2026-05-09 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSTL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='user_uploads/%Y/%m/%d/', verbose_name='Archivo STL')),
                ('nombre_archivo', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('UPLOADED', 'Subido - Pendiente de analisis'), ('CALCULATED', 'Precio calculado'), ('ERROR', 'Error en el archivo')], default='UPLOADED', max_length=20)),
                ('volume_cm3', models.FloatField(blank=True, null=True, verbose_name='Volumen (cm3)')),
                ('estimated_weight_gr', models.FloatField(blank=True, null=True, verbose_name='Peso (g)')),
                ('calculated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio calculado (euros)')),
                ('notas_cliente', models.TextField(blank=True, verbose_name='Instrucciones del cliente')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_stls', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'STL Personalizado',
                'verbose_name_plural': 'STLs Personalizados',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
