# Generated by Django 4.2.30 on 2026-05-09 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('tipo', models.CharField(choices=[('modelo', 'Modelo 3D'), ('filamento', 'Filamento'), ('consumible', 'Consumible')], default='modelo', max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='categories/')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio base (euros)')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock disponible')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Imagen')),
                ('activo', models.BooleanField(default=True, verbose_name='Visible en tienda')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='STLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='stl_models/', verbose_name='Archivo STL')),
                ('volume_cm3', models.FloatField(blank=True, null=True, verbose_name='Volumen (cm3)')),
                ('weight_gr', models.FloatField(blank=True, null=True, verbose_name='Peso estimado (g)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stl_model', to='store.product')),
            ],
            options={
                'verbose_name': 'Modelo STL',
                'verbose_name_plural': 'Modelos STL',
            },
        ),
    ]
